version: '3'
services:
    nagios:
        image: jasonrivers/nagios:latest
        container_name: nagios
        build:
          tag:
            - valvarezo/infra-duoc:latest
        restart: always
        ports:
          - 9090:80
        volumes:
          - ./config/nagios/etc/:/opt/nagios/etc/
          - ./config/nagios/var/:/opt/nagios/var/
          - ./config/apache2/:/etc/apache2/sites-available/