version: '3'
services:
    nagios:
        image: jasonrivers/nagios:latest
        container_name: nagios
        restart: always
        ports:
          - 9090:80
        volumes:
          - ./config/nagios/etc/:/opt/nagios/etc/
          - ./config/apache2/nagios.conf:/etc/apache2/sites-available/nagios.conf